package com.ei.itop.common.dbentity;

public class CcCust {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.SUP_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long supCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.CUST_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String custCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Short orgLevel;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String orgLvlPath;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String custName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String shortName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String domainName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String domainNameSec;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String notes;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.CC_CUST_ID
     *
     * @return the value of CC_CUST.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.CC_CUST_ID
     *
     * @param ccCustId the value for CC_CUST.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.SC_ORG_ID
     *
     * @return the value of CC_CUST.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.SC_ORG_ID
     *
     * @param scOrgId the value for CC_CUST.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.SC_ORG_NAME
     *
     * @return the value of CC_CUST.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.SC_ORG_NAME
     *
     * @param scOrgName the value for CC_CUST.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.SUP_CUST_ID
     *
     * @return the value of CC_CUST.SUP_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getSupCustId() {
        return supCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.SUP_CUST_ID
     *
     * @param supCustId the value for CC_CUST.SUP_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setSupCustId(Long supCustId) {
        this.supCustId = supCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.CUST_CODE
     *
     * @return the value of CC_CUST.CUST_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.CUST_CODE
     *
     * @param custCode the value for CC_CUST.CUST_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.ORG_LEVEL
     *
     * @return the value of CC_CUST.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Short getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.ORG_LEVEL
     *
     * @param orgLevel the value for CC_CUST.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOrgLevel(Short orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.ORG_LVL_PATH
     *
     * @return the value of CC_CUST.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getOrgLvlPath() {
        return orgLvlPath;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.ORG_LVL_PATH
     *
     * @param orgLvlPath the value for CC_CUST.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOrgLvlPath(String orgLvlPath) {
        this.orgLvlPath = orgLvlPath;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.CUST_NAME
     *
     * @return the value of CC_CUST.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.CUST_NAME
     *
     * @param custName the value for CC_CUST.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.SHORT_NAME
     *
     * @return the value of CC_CUST.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.SHORT_NAME
     *
     * @param shortName the value for CC_CUST.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.LAST_NAME
     *
     * @return the value of CC_CUST.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.LAST_NAME
     *
     * @param lastName the value for CC_CUST.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.DOMAIN_NAME
     *
     * @return the value of CC_CUST.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.DOMAIN_NAME
     *
     * @param domainName the value for CC_CUST.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.DOMAIN_NAME_SEC
     *
     * @return the value of CC_CUST.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getDomainNameSec() {
        return domainNameSec;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.DOMAIN_NAME_SEC
     *
     * @param domainNameSec the value for CC_CUST.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setDomainNameSec(String domainNameSec) {
        this.domainNameSec = domainNameSec;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.NOTES
     *
     * @return the value of CC_CUST.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.NOTES
     *
     * @param notes the value for CC_CUST.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST.STATE
     *
     * @return the value of CC_CUST.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST.STATE
     *
     * @param state the value for CC_CUST.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}