package com.ei.itop.common.dbentity;

public class CcCustProdOp {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String custName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scModuleId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String moduleName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOpId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String loginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scJobId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String jobName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String jobClass;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD_OP.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String jobLevel;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.CC_CUST_ID
     *
     * @return the value of CC_CUST_PROD_OP.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.CC_CUST_ID
     *
     * @param ccCustId the value for CC_CUST_PROD_OP.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.CUST_NAME
     *
     * @return the value of CC_CUST_PROD_OP.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.CUST_NAME
     *
     * @param custName the value for CC_CUST_PROD_OP.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_ORG_ID
     *
     * @return the value of CC_CUST_PROD_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_ORG_ID
     *
     * @param scOrgId the value for CC_CUST_PROD_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_ORG_NAME
     *
     * @return the value of CC_CUST_PROD_OP.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_ORG_NAME
     *
     * @param scOrgName the value for CC_CUST_PROD_OP.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_PRODUCT_ID
     *
     * @return the value of CC_CUST_PROD_OP.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_PRODUCT_ID
     *
     * @param scProductId the value for CC_CUST_PROD_OP.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.PROD_NAME
     *
     * @return the value of CC_CUST_PROD_OP.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.PROD_NAME
     *
     * @param prodName the value for CC_CUST_PROD_OP.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_MODULE_ID
     *
     * @return the value of CC_CUST_PROD_OP.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScModuleId() {
        return scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_MODULE_ID
     *
     * @param scModuleId the value for CC_CUST_PROD_OP.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScModuleId(Long scModuleId) {
        this.scModuleId = scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.MODULE_NAME
     *
     * @return the value of CC_CUST_PROD_OP.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.MODULE_NAME
     *
     * @param moduleName the value for CC_CUST_PROD_OP.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_OP_ID
     *
     * @return the value of CC_CUST_PROD_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOpId() {
        return scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_OP_ID
     *
     * @param scOpId the value for CC_CUST_PROD_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOpId(Long scOpId) {
        this.scOpId = scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.LOGIN_CODE
     *
     * @return the value of CC_CUST_PROD_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.LOGIN_CODE
     *
     * @param loginCode the value for CC_CUST_PROD_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.SC_JOB_ID
     *
     * @return the value of CC_CUST_PROD_OP.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScJobId() {
        return scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.SC_JOB_ID
     *
     * @param scJobId the value for CC_CUST_PROD_OP.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScJobId(Long scJobId) {
        this.scJobId = scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.JOB_NAME
     *
     * @return the value of CC_CUST_PROD_OP.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.JOB_NAME
     *
     * @param jobName the value for CC_CUST_PROD_OP.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.JOB_CLASS
     *
     * @return the value of CC_CUST_PROD_OP.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.JOB_CLASS
     *
     * @param jobClass the value for CC_CUST_PROD_OP.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD_OP.JOB_LEVEL
     *
     * @return the value of CC_CUST_PROD_OP.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getJobLevel() {
        return jobLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD_OP.JOB_LEVEL
     *
     * @param jobLevel the value for CC_CUST_PROD_OP.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setJobLevel(String jobLevel) {
        this.jobLevel = jobLevel;
    }
}