package com.ei.itop.common.dbentity;

import java.util.Date;

public class CcCustProd {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String custName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.SERVICE_START_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Date serviceStartDt;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_CUST_PROD.SERVICE_END_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Date serviceEndDt;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.CC_CUST_ID
     *
     * @return the value of CC_CUST_PROD.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.CC_CUST_ID
     *
     * @param ccCustId the value for CC_CUST_PROD.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.CUST_NAME
     *
     * @return the value of CC_CUST_PROD.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.CUST_NAME
     *
     * @param custName the value for CC_CUST_PROD.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.SC_ORG_ID
     *
     * @return the value of CC_CUST_PROD.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.SC_ORG_ID
     *
     * @param scOrgId the value for CC_CUST_PROD.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.SC_ORG_NAME
     *
     * @return the value of CC_CUST_PROD.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.SC_ORG_NAME
     *
     * @param scOrgName the value for CC_CUST_PROD.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.SC_PRODUCT_ID
     *
     * @return the value of CC_CUST_PROD.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.SC_PRODUCT_ID
     *
     * @param scProductId the value for CC_CUST_PROD.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.PROD_NAME
     *
     * @return the value of CC_CUST_PROD.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.PROD_NAME
     *
     * @param prodName the value for CC_CUST_PROD.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.SERVICE_START_DT
     *
     * @return the value of CC_CUST_PROD.SERVICE_START_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Date getServiceStartDt() {
        return serviceStartDt;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.SERVICE_START_DT
     *
     * @param serviceStartDt the value for CC_CUST_PROD.SERVICE_START_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setServiceStartDt(Date serviceStartDt) {
        this.serviceStartDt = serviceStartDt;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_CUST_PROD.SERVICE_END_DT
     *
     * @return the value of CC_CUST_PROD.SERVICE_END_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Date getServiceEndDt() {
        return serviceEndDt;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_CUST_PROD.SERVICE_END_DT
     *
     * @param serviceEndDt the value for CC_CUST_PROD.SERVICE_END_DT
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setServiceEndDt(Date serviceEndDt) {
        this.serviceEndDt = serviceEndDt;
    }
}