package com.ei.itop.common.dbentity;

public class CcSlo {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String custName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.PRIORITY_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String priorityCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.PRIORITY_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String priorityVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.COMPLEX_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String complexCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.COMPLEX_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String complexVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.RESPONSE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long responseTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_SLO.DEAL_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long dealTime;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.CC_CUST_ID
     *
     * @return the value of CC_SLO.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.CC_CUST_ID
     *
     * @param ccCustId the value for CC_SLO.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.CUST_NAME
     *
     * @return the value of CC_SLO.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.CUST_NAME
     *
     * @param custName the value for CC_SLO.CUST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.SC_ORG_ID
     *
     * @return the value of CC_SLO.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.SC_ORG_ID
     *
     * @param scOrgId the value for CC_SLO.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.SC_ORG_NAME
     *
     * @return the value of CC_SLO.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.SC_ORG_NAME
     *
     * @param scOrgName the value for CC_SLO.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.SC_PRODUCT_ID
     *
     * @return the value of CC_SLO.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.SC_PRODUCT_ID
     *
     * @param scProductId the value for CC_SLO.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.PROD_NAME
     *
     * @return the value of CC_SLO.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.PROD_NAME
     *
     * @param prodName the value for CC_SLO.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.PRIORITY_CODE
     *
     * @return the value of CC_SLO.PRIORITY_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getPriorityCode() {
        return priorityCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.PRIORITY_CODE
     *
     * @param priorityCode the value for CC_SLO.PRIORITY_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setPriorityCode(String priorityCode) {
        this.priorityCode = priorityCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.PRIORITY_VAL
     *
     * @return the value of CC_SLO.PRIORITY_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getPriorityVal() {
        return priorityVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.PRIORITY_VAL
     *
     * @param priorityVal the value for CC_SLO.PRIORITY_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setPriorityVal(String priorityVal) {
        this.priorityVal = priorityVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.COMPLEX_CODE
     *
     * @return the value of CC_SLO.COMPLEX_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getComplexCode() {
        return complexCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.COMPLEX_CODE
     *
     * @param complexCode the value for CC_SLO.COMPLEX_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setComplexCode(String complexCode) {
        this.complexCode = complexCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.COMPLEX_VAL
     *
     * @return the value of CC_SLO.COMPLEX_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getComplexVal() {
        return complexVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.COMPLEX_VAL
     *
     * @param complexVal the value for CC_SLO.COMPLEX_VAL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setComplexVal(String complexVal) {
        this.complexVal = complexVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.RESPONSE_TIME
     *
     * @return the value of CC_SLO.RESPONSE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.RESPONSE_TIME
     *
     * @param responseTime the value for CC_SLO.RESPONSE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setResponseTime(Long responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_SLO.DEAL_TIME
     *
     * @return the value of CC_SLO.DEAL_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_SLO.DEAL_TIME
     *
     * @param dealTime the value for CC_SLO.DEAL_TIME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setDealTime(Long dealTime) {
        this.dealTime = dealTime;
    }
}