package com.ei.itop.common.dbentity;

public class CcUser {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.CC_USER_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccUserId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.DEF_CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long defCcCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String opCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String loginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String loginPasswd;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String firstName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String opName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Short gender;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Short opKind;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String mobileNo;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String officeTel;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private String notes;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column CC_USER.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.CC_USER_ID
     *
     * @return the value of CC_USER.CC_USER_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcUserId() {
        return ccUserId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.CC_USER_ID
     *
     * @param ccUserId the value for CC_USER.CC_USER_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcUserId(Long ccUserId) {
        this.ccUserId = ccUserId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.CC_CUST_ID
     *
     * @return the value of CC_USER.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.CC_CUST_ID
     *
     * @param ccCustId the value for CC_USER.CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.DEF_CC_CUST_ID
     *
     * @return the value of CC_USER.DEF_CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getDefCcCustId() {
        return defCcCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.DEF_CC_CUST_ID
     *
     * @param defCcCustId the value for CC_USER.DEF_CC_CUST_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setDefCcCustId(Long defCcCustId) {
        this.defCcCustId = defCcCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.SC_ORG_ID
     *
     * @return the value of CC_USER.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.SC_ORG_ID
     *
     * @param scOrgId the value for CC_USER.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.SC_ORG_NAME
     *
     * @return the value of CC_USER.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.SC_ORG_NAME
     *
     * @param scOrgName the value for CC_USER.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.OP_CODE
     *
     * @return the value of CC_USER.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.OP_CODE
     *
     * @param opCode the value for CC_USER.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOpCode(String opCode) {
        this.opCode = opCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.LOGIN_CODE
     *
     * @return the value of CC_USER.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.LOGIN_CODE
     *
     * @param loginCode the value for CC_USER.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.LOGIN_PASSWD
     *
     * @return the value of CC_USER.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.LOGIN_PASSWD
     *
     * @param loginPasswd the value for CC_USER.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.FIRST_NAME
     *
     * @return the value of CC_USER.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.FIRST_NAME
     *
     * @param firstName the value for CC_USER.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.LAST_NAME
     *
     * @return the value of CC_USER.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.LAST_NAME
     *
     * @param lastName the value for CC_USER.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.OP_NAME
     *
     * @return the value of CC_USER.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.OP_NAME
     *
     * @param opName the value for CC_USER.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOpName(String opName) {
        this.opName = opName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.GENDER
     *
     * @return the value of CC_USER.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.GENDER
     *
     * @param gender the value for CC_USER.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.OP_KIND
     *
     * @return the value of CC_USER.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Short getOpKind() {
        return opKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.OP_KIND
     *
     * @param opKind the value for CC_USER.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOpKind(Short opKind) {
        this.opKind = opKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.MOBILE_NO
     *
     * @return the value of CC_USER.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.MOBILE_NO
     *
     * @param mobileNo the value for CC_USER.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.OFFICE_TEL
     *
     * @return the value of CC_USER.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getOfficeTel() {
        return officeTel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.OFFICE_TEL
     *
     * @param officeTel the value for CC_USER.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setOfficeTel(String officeTel) {
        this.officeTel = officeTel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.NOTES
     *
     * @return the value of CC_USER.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.NOTES
     *
     * @param notes the value for CC_USER.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column CC_USER.STATE
     *
     * @return the value of CC_USER.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column CC_USER.STATE
     *
     * @param state the value for CC_USER.STATE
     *
     * @abatorgenerated Mon Oct 13 12:04:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}