package com.ei.itop.common.dbentity;

public class IcAttach {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_ATTACH.IC_ATTACH_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long icAttachId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_ATTACH.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long icIncidentId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_ATTACH.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long transId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_ATTACH.ATTACH_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String attachPath;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_ATTACH.IC_ATTACH_ID
     *
     * @return the value of IC_ATTACH.IC_ATTACH_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getIcAttachId() {
        return icAttachId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_ATTACH.IC_ATTACH_ID
     *
     * @param icAttachId the value for IC_ATTACH.IC_ATTACH_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setIcAttachId(Long icAttachId) {
        this.icAttachId = icAttachId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_ATTACH.IC_INCIDENT_ID
     *
     * @return the value of IC_ATTACH.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getIcIncidentId() {
        return icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_ATTACH.IC_INCIDENT_ID
     *
     * @param icIncidentId the value for IC_ATTACH.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setIcIncidentId(Long icIncidentId) {
        this.icIncidentId = icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_ATTACH.TRANS_ID
     *
     * @return the value of IC_ATTACH.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getTransId() {
        return transId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_ATTACH.TRANS_ID
     *
     * @param transId the value for IC_ATTACH.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setTransId(Long transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_ATTACH.ATTACH_PATH
     *
     * @return the value of IC_ATTACH.ATTACH_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getAttachPath() {
        return attachPath;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_ATTACH.ATTACH_PATH
     *
     * @param attachPath the value for IC_ATTACH.ATTACH_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setAttachPath(String attachPath) {
        this.attachPath = attachPath;
    }
}