package com.ei.itop.common.dbentity;

import java.util.Date;

public class IcIncident {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IC_INCIDENT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long icIncidentId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.INCIDENT_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String incidentCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_ORG_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_ORG_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CC_CUST_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long ccCustId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CUST_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String custName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_PRODUCT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PROD_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_MODULE_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long scModuleId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.MODULE_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String moduleName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PL_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String plObjectType;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PL_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long plObjectId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PL_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String plLoginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PL_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String plObjectName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_OP_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long scOpId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String scLoginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SC_LOGIN_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String scLoginName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IC_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String icObjectType;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IC_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long icObjectId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IC_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String icObjectName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String icLoginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.REGISTE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date registeTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.HAPPEN_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date happenTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SOURCE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String sourceCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.SOURCE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String sourceVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CLASS_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String classCodeUser;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CLASS_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String classValUser;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.AFFECT_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String affectCodeUser;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.AFFECT_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String affectValUser;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CLASS_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String classCodeOp;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CLASS_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String classValOp;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.AFFECT_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String affectCodeOp;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.AFFECT_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String affectValOp;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.COMPLEX_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String complexCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.COMPLEX_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String complexVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PRIORITY_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String priorityCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.PRIORITY_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String priorityVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CC_LIST
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String ccList;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.BRIEF
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String brief;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DETAIL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String detail;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.RESPONSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long responseTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DEAL_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long dealTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.REPONSE_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date reponseDur2;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DEAL_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date dealDur2;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.REPONSE_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String reponseNum;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DEAL_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String dealNum;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.RESTORE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date restoreTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.REPONSE_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long reponseDur;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DEAL_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long dealDur;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FINISH_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date finishTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IT_SOLUTION
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String itSolution;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FINISH_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String finishCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FINISH_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String finishVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FEEDBACK_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String feedbackCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FEEDBACK_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String feedbackVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.FEEDBACK_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date feedbackTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CLOSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date closeTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IT_PHASE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String itPhase;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IT_STATE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String itStateCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.IT_STATE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String itStateVal;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.DATA_STATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Long dataState;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CREATOR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String creator;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.CREATE_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.MODIFIER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private String modifier;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_INCIDENT.MODIFY_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    private Date modifyDate;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IC_INCIDENT_ID
     *
     * @return the value of IC_INCIDENT.IC_INCIDENT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getIcIncidentId() {
        return icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IC_INCIDENT_ID
     *
     * @param icIncidentId the value for IC_INCIDENT.IC_INCIDENT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIcIncidentId(Long icIncidentId) {
        this.icIncidentId = icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.INCIDENT_CODE
     *
     * @return the value of IC_INCIDENT.INCIDENT_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getIncidentCode() {
        return incidentCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.INCIDENT_CODE
     *
     * @param incidentCode the value for IC_INCIDENT.INCIDENT_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIncidentCode(String incidentCode) {
        this.incidentCode = incidentCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_ORG_ID
     *
     * @return the value of IC_INCIDENT.SC_ORG_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_ORG_ID
     *
     * @param scOrgId the value for IC_INCIDENT.SC_ORG_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_ORG_NAME
     *
     * @return the value of IC_INCIDENT.SC_ORG_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_ORG_NAME
     *
     * @param scOrgName the value for IC_INCIDENT.SC_ORG_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CC_CUST_ID
     *
     * @return the value of IC_INCIDENT.CC_CUST_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getCcCustId() {
        return ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CC_CUST_ID
     *
     * @param ccCustId the value for IC_INCIDENT.CC_CUST_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCcCustId(Long ccCustId) {
        this.ccCustId = ccCustId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CUST_NAME
     *
     * @return the value of IC_INCIDENT.CUST_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CUST_NAME
     *
     * @param custName the value for IC_INCIDENT.CUST_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_PRODUCT_ID
     *
     * @return the value of IC_INCIDENT.SC_PRODUCT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_PRODUCT_ID
     *
     * @param scProductId the value for IC_INCIDENT.SC_PRODUCT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PROD_NAME
     *
     * @return the value of IC_INCIDENT.PROD_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PROD_NAME
     *
     * @param prodName the value for IC_INCIDENT.PROD_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_MODULE_ID
     *
     * @return the value of IC_INCIDENT.SC_MODULE_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getScModuleId() {
        return scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_MODULE_ID
     *
     * @param scModuleId the value for IC_INCIDENT.SC_MODULE_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScModuleId(Long scModuleId) {
        this.scModuleId = scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.MODULE_NAME
     *
     * @return the value of IC_INCIDENT.MODULE_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.MODULE_NAME
     *
     * @param moduleName the value for IC_INCIDENT.MODULE_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PL_OBJECT_TYPE
     *
     * @return the value of IC_INCIDENT.PL_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getPlObjectType() {
        return plObjectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PL_OBJECT_TYPE
     *
     * @param plObjectType the value for IC_INCIDENT.PL_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPlObjectType(String plObjectType) {
        this.plObjectType = plObjectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PL_OBJECT_ID
     *
     * @return the value of IC_INCIDENT.PL_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getPlObjectId() {
        return plObjectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PL_OBJECT_ID
     *
     * @param plObjectId the value for IC_INCIDENT.PL_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPlObjectId(Long plObjectId) {
        this.plObjectId = plObjectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PL_LOGIN_CODE
     *
     * @return the value of IC_INCIDENT.PL_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getPlLoginCode() {
        return plLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PL_LOGIN_CODE
     *
     * @param plLoginCode the value for IC_INCIDENT.PL_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPlLoginCode(String plLoginCode) {
        this.plLoginCode = plLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PL_OBJECT_NAME
     *
     * @return the value of IC_INCIDENT.PL_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getPlObjectName() {
        return plObjectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PL_OBJECT_NAME
     *
     * @param plObjectName the value for IC_INCIDENT.PL_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPlObjectName(String plObjectName) {
        this.plObjectName = plObjectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_OP_ID
     *
     * @return the value of IC_INCIDENT.SC_OP_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getScOpId() {
        return scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_OP_ID
     *
     * @param scOpId the value for IC_INCIDENT.SC_OP_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScOpId(Long scOpId) {
        this.scOpId = scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_LOGIN_CODE
     *
     * @return the value of IC_INCIDENT.SC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getScLoginCode() {
        return scLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_LOGIN_CODE
     *
     * @param scLoginCode the value for IC_INCIDENT.SC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScLoginCode(String scLoginCode) {
        this.scLoginCode = scLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SC_LOGIN_NAME
     *
     * @return the value of IC_INCIDENT.SC_LOGIN_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getScLoginName() {
        return scLoginName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SC_LOGIN_NAME
     *
     * @param scLoginName the value for IC_INCIDENT.SC_LOGIN_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setScLoginName(String scLoginName) {
        this.scLoginName = scLoginName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IC_OBJECT_TYPE
     *
     * @return the value of IC_INCIDENT.IC_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getIcObjectType() {
        return icObjectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IC_OBJECT_TYPE
     *
     * @param icObjectType the value for IC_INCIDENT.IC_OBJECT_TYPE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIcObjectType(String icObjectType) {
        this.icObjectType = icObjectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IC_OBJECT_ID
     *
     * @return the value of IC_INCIDENT.IC_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getIcObjectId() {
        return icObjectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IC_OBJECT_ID
     *
     * @param icObjectId the value for IC_INCIDENT.IC_OBJECT_ID
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIcObjectId(Long icObjectId) {
        this.icObjectId = icObjectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IC_OBJECT_NAME
     *
     * @return the value of IC_INCIDENT.IC_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getIcObjectName() {
        return icObjectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IC_OBJECT_NAME
     *
     * @param icObjectName the value for IC_INCIDENT.IC_OBJECT_NAME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIcObjectName(String icObjectName) {
        this.icObjectName = icObjectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IC_LOGIN_CODE
     *
     * @return the value of IC_INCIDENT.IC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getIcLoginCode() {
        return icLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IC_LOGIN_CODE
     *
     * @param icLoginCode the value for IC_INCIDENT.IC_LOGIN_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setIcLoginCode(String icLoginCode) {
        this.icLoginCode = icLoginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.REGISTE_TIME
     *
     * @return the value of IC_INCIDENT.REGISTE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getRegisteTime() {
        return registeTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.REGISTE_TIME
     *
     * @param registeTime the value for IC_INCIDENT.REGISTE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setRegisteTime(Date registeTime) {
        this.registeTime = registeTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.HAPPEN_TIME
     *
     * @return the value of IC_INCIDENT.HAPPEN_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getHappenTime() {
        return happenTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.HAPPEN_TIME
     *
     * @param happenTime the value for IC_INCIDENT.HAPPEN_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setHappenTime(Date happenTime) {
        this.happenTime = happenTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SOURCE_CODE
     *
     * @return the value of IC_INCIDENT.SOURCE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SOURCE_CODE
     *
     * @param sourceCode the value for IC_INCIDENT.SOURCE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.SOURCE_VAL
     *
     * @return the value of IC_INCIDENT.SOURCE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getSourceVal() {
        return sourceVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.SOURCE_VAL
     *
     * @param sourceVal the value for IC_INCIDENT.SOURCE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setSourceVal(String sourceVal) {
        this.sourceVal = sourceVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CLASS_CODE_USER
     *
     * @return the value of IC_INCIDENT.CLASS_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getClassCodeUser() {
        return classCodeUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CLASS_CODE_USER
     *
     * @param classCodeUser the value for IC_INCIDENT.CLASS_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setClassCodeUser(String classCodeUser) {
        this.classCodeUser = classCodeUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CLASS_VAL_USER
     *
     * @return the value of IC_INCIDENT.CLASS_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getClassValUser() {
        return classValUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CLASS_VAL_USER
     *
     * @param classValUser the value for IC_INCIDENT.CLASS_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setClassValUser(String classValUser) {
        this.classValUser = classValUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.AFFECT_CODE_USER
     *
     * @return the value of IC_INCIDENT.AFFECT_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getAffectCodeUser() {
        return affectCodeUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.AFFECT_CODE_USER
     *
     * @param affectCodeUser the value for IC_INCIDENT.AFFECT_CODE_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setAffectCodeUser(String affectCodeUser) {
        this.affectCodeUser = affectCodeUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.AFFECT_VAL_USER
     *
     * @return the value of IC_INCIDENT.AFFECT_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getAffectValUser() {
        return affectValUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.AFFECT_VAL_USER
     *
     * @param affectValUser the value for IC_INCIDENT.AFFECT_VAL_USER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setAffectValUser(String affectValUser) {
        this.affectValUser = affectValUser;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CLASS_CODE_OP
     *
     * @return the value of IC_INCIDENT.CLASS_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getClassCodeOp() {
        return classCodeOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CLASS_CODE_OP
     *
     * @param classCodeOp the value for IC_INCIDENT.CLASS_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setClassCodeOp(String classCodeOp) {
        this.classCodeOp = classCodeOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CLASS_VAL_OP
     *
     * @return the value of IC_INCIDENT.CLASS_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getClassValOp() {
        return classValOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CLASS_VAL_OP
     *
     * @param classValOp the value for IC_INCIDENT.CLASS_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setClassValOp(String classValOp) {
        this.classValOp = classValOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.AFFECT_CODE_OP
     *
     * @return the value of IC_INCIDENT.AFFECT_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getAffectCodeOp() {
        return affectCodeOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.AFFECT_CODE_OP
     *
     * @param affectCodeOp the value for IC_INCIDENT.AFFECT_CODE_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setAffectCodeOp(String affectCodeOp) {
        this.affectCodeOp = affectCodeOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.AFFECT_VAL_OP
     *
     * @return the value of IC_INCIDENT.AFFECT_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getAffectValOp() {
        return affectValOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.AFFECT_VAL_OP
     *
     * @param affectValOp the value for IC_INCIDENT.AFFECT_VAL_OP
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setAffectValOp(String affectValOp) {
        this.affectValOp = affectValOp;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.COMPLEX_CODE
     *
     * @return the value of IC_INCIDENT.COMPLEX_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getComplexCode() {
        return complexCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.COMPLEX_CODE
     *
     * @param complexCode the value for IC_INCIDENT.COMPLEX_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setComplexCode(String complexCode) {
        this.complexCode = complexCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.COMPLEX_VAL
     *
     * @return the value of IC_INCIDENT.COMPLEX_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getComplexVal() {
        return complexVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.COMPLEX_VAL
     *
     * @param complexVal the value for IC_INCIDENT.COMPLEX_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setComplexVal(String complexVal) {
        this.complexVal = complexVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PRIORITY_CODE
     *
     * @return the value of IC_INCIDENT.PRIORITY_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getPriorityCode() {
        return priorityCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PRIORITY_CODE
     *
     * @param priorityCode the value for IC_INCIDENT.PRIORITY_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPriorityCode(String priorityCode) {
        this.priorityCode = priorityCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.PRIORITY_VAL
     *
     * @return the value of IC_INCIDENT.PRIORITY_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getPriorityVal() {
        return priorityVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.PRIORITY_VAL
     *
     * @param priorityVal the value for IC_INCIDENT.PRIORITY_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setPriorityVal(String priorityVal) {
        this.priorityVal = priorityVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CC_LIST
     *
     * @return the value of IC_INCIDENT.CC_LIST
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getCcList() {
        return ccList;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CC_LIST
     *
     * @param ccList the value for IC_INCIDENT.CC_LIST
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCcList(String ccList) {
        this.ccList = ccList;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.BRIEF
     *
     * @return the value of IC_INCIDENT.BRIEF
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.BRIEF
     *
     * @param brief the value for IC_INCIDENT.BRIEF
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DETAIL
     *
     * @return the value of IC_INCIDENT.DETAIL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DETAIL
     *
     * @param detail the value for IC_INCIDENT.DETAIL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.RESPONSE_TIME
     *
     * @return the value of IC_INCIDENT.RESPONSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.RESPONSE_TIME
     *
     * @param responseTime the value for IC_INCIDENT.RESPONSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setResponseTime(Long responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DEAL_TIME
     *
     * @return the value of IC_INCIDENT.DEAL_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DEAL_TIME
     *
     * @param dealTime the value for IC_INCIDENT.DEAL_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDealTime(Long dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.REPONSE_DUR2
     *
     * @return the value of IC_INCIDENT.REPONSE_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getReponseDur2() {
        return reponseDur2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.REPONSE_DUR2
     *
     * @param reponseDur2 the value for IC_INCIDENT.REPONSE_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setReponseDur2(Date reponseDur2) {
        this.reponseDur2 = reponseDur2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DEAL_DUR2
     *
     * @return the value of IC_INCIDENT.DEAL_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getDealDur2() {
        return dealDur2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DEAL_DUR2
     *
     * @param dealDur2 the value for IC_INCIDENT.DEAL_DUR2
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDealDur2(Date dealDur2) {
        this.dealDur2 = dealDur2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.REPONSE_NUM
     *
     * @return the value of IC_INCIDENT.REPONSE_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getReponseNum() {
        return reponseNum;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.REPONSE_NUM
     *
     * @param reponseNum the value for IC_INCIDENT.REPONSE_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setReponseNum(String reponseNum) {
        this.reponseNum = reponseNum;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DEAL_NUM
     *
     * @return the value of IC_INCIDENT.DEAL_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getDealNum() {
        return dealNum;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DEAL_NUM
     *
     * @param dealNum the value for IC_INCIDENT.DEAL_NUM
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDealNum(String dealNum) {
        this.dealNum = dealNum;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.RESTORE_TIME
     *
     * @return the value of IC_INCIDENT.RESTORE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getRestoreTime() {
        return restoreTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.RESTORE_TIME
     *
     * @param restoreTime the value for IC_INCIDENT.RESTORE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setRestoreTime(Date restoreTime) {
        this.restoreTime = restoreTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.REPONSE_DUR
     *
     * @return the value of IC_INCIDENT.REPONSE_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getReponseDur() {
        return reponseDur;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.REPONSE_DUR
     *
     * @param reponseDur the value for IC_INCIDENT.REPONSE_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setReponseDur(Long reponseDur) {
        this.reponseDur = reponseDur;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DEAL_DUR
     *
     * @return the value of IC_INCIDENT.DEAL_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getDealDur() {
        return dealDur;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DEAL_DUR
     *
     * @param dealDur the value for IC_INCIDENT.DEAL_DUR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDealDur(Long dealDur) {
        this.dealDur = dealDur;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FINISH_TIME
     *
     * @return the value of IC_INCIDENT.FINISH_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FINISH_TIME
     *
     * @param finishTime the value for IC_INCIDENT.FINISH_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IT_SOLUTION
     *
     * @return the value of IC_INCIDENT.IT_SOLUTION
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getItSolution() {
        return itSolution;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IT_SOLUTION
     *
     * @param itSolution the value for IC_INCIDENT.IT_SOLUTION
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setItSolution(String itSolution) {
        this.itSolution = itSolution;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FINISH_CODE
     *
     * @return the value of IC_INCIDENT.FINISH_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getFinishCode() {
        return finishCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FINISH_CODE
     *
     * @param finishCode the value for IC_INCIDENT.FINISH_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFinishCode(String finishCode) {
        this.finishCode = finishCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FINISH_VAL
     *
     * @return the value of IC_INCIDENT.FINISH_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getFinishVal() {
        return finishVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FINISH_VAL
     *
     * @param finishVal the value for IC_INCIDENT.FINISH_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFinishVal(String finishVal) {
        this.finishVal = finishVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FEEDBACK_CODE
     *
     * @return the value of IC_INCIDENT.FEEDBACK_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getFeedbackCode() {
        return feedbackCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FEEDBACK_CODE
     *
     * @param feedbackCode the value for IC_INCIDENT.FEEDBACK_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFeedbackCode(String feedbackCode) {
        this.feedbackCode = feedbackCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FEEDBACK_VAL
     *
     * @return the value of IC_INCIDENT.FEEDBACK_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getFeedbackVal() {
        return feedbackVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FEEDBACK_VAL
     *
     * @param feedbackVal the value for IC_INCIDENT.FEEDBACK_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFeedbackVal(String feedbackVal) {
        this.feedbackVal = feedbackVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.FEEDBACK_TIME
     *
     * @return the value of IC_INCIDENT.FEEDBACK_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.FEEDBACK_TIME
     *
     * @param feedbackTime the value for IC_INCIDENT.FEEDBACK_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CLOSE_TIME
     *
     * @return the value of IC_INCIDENT.CLOSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CLOSE_TIME
     *
     * @param closeTime the value for IC_INCIDENT.CLOSE_TIME
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IT_PHASE
     *
     * @return the value of IC_INCIDENT.IT_PHASE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getItPhase() {
        return itPhase;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IT_PHASE
     *
     * @param itPhase the value for IC_INCIDENT.IT_PHASE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setItPhase(String itPhase) {
        this.itPhase = itPhase;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IT_STATE_CODE
     *
     * @return the value of IC_INCIDENT.IT_STATE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getItStateCode() {
        return itStateCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IT_STATE_CODE
     *
     * @param itStateCode the value for IC_INCIDENT.IT_STATE_CODE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setItStateCode(String itStateCode) {
        this.itStateCode = itStateCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.IT_STATE_VAL
     *
     * @return the value of IC_INCIDENT.IT_STATE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getItStateVal() {
        return itStateVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.IT_STATE_VAL
     *
     * @param itStateVal the value for IC_INCIDENT.IT_STATE_VAL
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setItStateVal(String itStateVal) {
        this.itStateVal = itStateVal;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.DATA_STATE
     *
     * @return the value of IC_INCIDENT.DATA_STATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Long getDataState() {
        return dataState;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.DATA_STATE
     *
     * @param dataState the value for IC_INCIDENT.DATA_STATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setDataState(Long dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CREATOR
     *
     * @return the value of IC_INCIDENT.CREATOR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CREATOR
     *
     * @param creator the value for IC_INCIDENT.CREATOR
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.CREATE_DATE
     *
     * @return the value of IC_INCIDENT.CREATE_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.CREATE_DATE
     *
     * @param createDate the value for IC_INCIDENT.CREATE_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.MODIFIER
     *
     * @return the value of IC_INCIDENT.MODIFIER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.MODIFIER
     *
     * @param modifier the value for IC_INCIDENT.MODIFIER
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_INCIDENT.MODIFY_DATE
     *
     * @return the value of IC_INCIDENT.MODIFY_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_INCIDENT.MODIFY_DATE
     *
     * @param modifyDate the value for IC_INCIDENT.MODIFY_DATE
     *
     * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}