package com.ei.itop.common.dbentity;

import java.util.Date;

public class IcTransaction {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long transId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long icIncidentId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.CREATE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.OBJECT_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String objectType;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.OBJECT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long objectId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String loginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.OBJECT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String objectName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.IT_PHASE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String itPhase;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.TRANS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String transType;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.CONTENTS
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String contents;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long scOpId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.LOGIN_CODE2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String loginCode2;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column IC_TRANSACTION.OP_NAME2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String opName2;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.TRANS_ID
     *
     * @return the value of IC_TRANSACTION.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getTransId() {
        return transId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.TRANS_ID
     *
     * @param transId the value for IC_TRANSACTION.TRANS_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setTransId(Long transId) {
        this.transId = transId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.IC_INCIDENT_ID
     *
     * @return the value of IC_TRANSACTION.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getIcIncidentId() {
        return icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.IC_INCIDENT_ID
     *
     * @param icIncidentId the value for IC_TRANSACTION.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setIcIncidentId(Long icIncidentId) {
        this.icIncidentId = icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.CREATE_TIME
     *
     * @return the value of IC_TRANSACTION.CREATE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.CREATE_TIME
     *
     * @param createTime the value for IC_TRANSACTION.CREATE_TIME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.OBJECT_TYPE
     *
     * @return the value of IC_TRANSACTION.OBJECT_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.OBJECT_TYPE
     *
     * @param objectType the value for IC_TRANSACTION.OBJECT_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.OBJECT_ID
     *
     * @return the value of IC_TRANSACTION.OBJECT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.OBJECT_ID
     *
     * @param objectId the value for IC_TRANSACTION.OBJECT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.LOGIN_CODE
     *
     * @return the value of IC_TRANSACTION.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.LOGIN_CODE
     *
     * @param loginCode the value for IC_TRANSACTION.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.OBJECT_NAME
     *
     * @return the value of IC_TRANSACTION.OBJECT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.OBJECT_NAME
     *
     * @param objectName the value for IC_TRANSACTION.OBJECT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.IT_PHASE
     *
     * @return the value of IC_TRANSACTION.IT_PHASE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getItPhase() {
        return itPhase;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.IT_PHASE
     *
     * @param itPhase the value for IC_TRANSACTION.IT_PHASE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setItPhase(String itPhase) {
        this.itPhase = itPhase;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.TRANS_TYPE
     *
     * @return the value of IC_TRANSACTION.TRANS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.TRANS_TYPE
     *
     * @param transType the value for IC_TRANSACTION.TRANS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.CONTENTS
     *
     * @return the value of IC_TRANSACTION.CONTENTS
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.CONTENTS
     *
     * @param contents the value for IC_TRANSACTION.CONTENTS
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.SC_OP_ID
     *
     * @return the value of IC_TRANSACTION.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getScOpId() {
        return scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.SC_OP_ID
     *
     * @param scOpId the value for IC_TRANSACTION.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setScOpId(Long scOpId) {
        this.scOpId = scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.LOGIN_CODE2
     *
     * @return the value of IC_TRANSACTION.LOGIN_CODE2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getLoginCode2() {
        return loginCode2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.LOGIN_CODE2
     *
     * @param loginCode2 the value for IC_TRANSACTION.LOGIN_CODE2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setLoginCode2(String loginCode2) {
        this.loginCode2 = loginCode2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column IC_TRANSACTION.OP_NAME2
     *
     * @return the value of IC_TRANSACTION.OP_NAME2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getOpName2() {
        return opName2;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column IC_TRANSACTION.OP_NAME2
     *
     * @param opName2 the value for IC_TRANSACTION.OP_NAME2
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setOpName2(String opName2) {
        this.opName2 = opName2;
    }
}