package com.ei.itop.common.dbentity;

import java.util.Date;

public class IcTransaction {

	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.TRANS_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private Long transId;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.IC_INCIDENT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private Long icIncidentId;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.CREATE_TIME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.OBJECT_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String objectType;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.OBJECT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private Long objectId;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.LOGIN_CODE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String loginCode;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.OBJECT_NAME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String objectName;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.IT_PHASE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String itPhase;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.TRANS_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String transType;
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds to the database column IC_TRANSACTION.CONTENTS
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	private String contents;

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.TRANS_ID
	 * @return  the value of IC_TRANSACTION.TRANS_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public Long getTransId() {
		return transId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.TRANS_ID
	 * @param transId  the value for IC_TRANSACTION.TRANS_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setTransId(Long transId) {
		this.transId = transId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.IC_INCIDENT_ID
	 * @return  the value of IC_TRANSACTION.IC_INCIDENT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public Long getIcIncidentId() {
		return icIncidentId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.IC_INCIDENT_ID
	 * @param icIncidentId  the value for IC_TRANSACTION.IC_INCIDENT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setIcIncidentId(Long icIncidentId) {
		this.icIncidentId = icIncidentId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.CREATE_TIME
	 * @return  the value of IC_TRANSACTION.CREATE_TIME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.CREATE_TIME
	 * @param createTime  the value for IC_TRANSACTION.CREATE_TIME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.OBJECT_TYPE
	 * @return  the value of IC_TRANSACTION.OBJECT_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getObjectType() {
		return objectType;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.OBJECT_TYPE
	 * @param objectType  the value for IC_TRANSACTION.OBJECT_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.OBJECT_ID
	 * @return  the value of IC_TRANSACTION.OBJECT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public Long getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.OBJECT_ID
	 * @param objectId  the value for IC_TRANSACTION.OBJECT_ID
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.LOGIN_CODE
	 * @return  the value of IC_TRANSACTION.LOGIN_CODE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getLoginCode() {
		return loginCode;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.LOGIN_CODE
	 * @param loginCode  the value for IC_TRANSACTION.LOGIN_CODE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setLoginCode(String loginCode) {
		this.loginCode = loginCode;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.OBJECT_NAME
	 * @return  the value of IC_TRANSACTION.OBJECT_NAME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getObjectName() {
		return objectName;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.OBJECT_NAME
	 * @param objectName  the value for IC_TRANSACTION.OBJECT_NAME
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.IT_PHASE
	 * @return  the value of IC_TRANSACTION.IT_PHASE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getItPhase() {
		return itPhase;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.IT_PHASE
	 * @param itPhase  the value for IC_TRANSACTION.IT_PHASE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setItPhase(String itPhase) {
		this.itPhase = itPhase;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.TRANS_TYPE
	 * @return  the value of IC_TRANSACTION.TRANS_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getTransType() {
		return transType;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.TRANS_TYPE
	 * @param transType  the value for IC_TRANSACTION.TRANS_TYPE
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setTransType(String transType) {
		this.transType = transType;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method returns the value of the database column IC_TRANSACTION.CONTENTS
	 * @return  the value of IC_TRANSACTION.CONTENTS
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by AILK AUTOMATIC TOOLS. This method sets the value of the database column IC_TRANSACTION.CONTENTS
	 * @param contents  the value for IC_TRANSACTION.CONTENTS
	 * @abatorgenerated  Tue Oct 14 19:49:21 CST 2014
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}
}