package com.ei.itop.common.dbentity;

import java.util.Date;

public class ScHoliday {
	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds
	 * to the database column SC_HOLIDAY.SC_ORG_ID
	 * 
	 * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
	 */
	private Long scOrgId;

	/**
	 * This field was generated by AILK AUTOMATIC TOOLS. This field corresponds
	 * to the database column SC_HOLIDAY.HOLIDAY
	 * 
	 * @abatorgenerated Wed Oct 15 20:00:47 CST 2014
	 */
	private Date holiday;

	/**
	 * @return the scOrgId
	 */
	public Long getScOrgId() {
		return scOrgId;
	}

	/**
	 * @param scOrgId
	 *            the scOrgId to set
	 */
	public void setScOrgId(Long scOrgId) {
		this.scOrgId = scOrgId;
	}

	/**
	 * @return the holiday
	 */
	public Date getHoliday() {
		return holiday;
	}

	/**
	 * @param holiday
	 *            the holiday to set
	 */
	public void setHoliday(Date holiday) {
		this.holiday = holiday;
	}
}