package com.ei.itop.common.dbentity;

public class ScJobI18n {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB_I18N.SC_JOB_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    private Long scJobId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    private String langFlag;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB_I18N.JOB_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    private String jobName;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB_I18N.SC_JOB_ID
     *
     * @return the value of SC_JOB_I18N.SC_JOB_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public Long getScJobId() {
        return scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB_I18N.SC_JOB_ID
     *
     * @param scJobId the value for SC_JOB_I18N.SC_JOB_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public void setScJobId(Long scJobId) {
        this.scJobId = scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB_I18N.LANG_FLAG
     *
     * @return the value of SC_JOB_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public String getLangFlag() {
        return langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB_I18N.LANG_FLAG
     *
     * @param langFlag the value for SC_JOB_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public void setLangFlag(String langFlag) {
        this.langFlag = langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB_I18N.JOB_NAME
     *
     * @return the value of SC_JOB_I18N.JOB_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB_I18N.JOB_NAME
     *
     * @param jobName the value for SC_JOB_I18N.JOB_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:44 CST 2014
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
}