package com.ei.itop.common.dbentity;

public class ScJob {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scJobId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.JOB_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String jobCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String jobName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String jobClass;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_JOB.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String jobLevel;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.SC_JOB_ID
     *
     * @return the value of SC_JOB.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScJobId() {
        return scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.SC_JOB_ID
     *
     * @param scJobId the value for SC_JOB.SC_JOB_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScJobId(Long scJobId) {
        this.scJobId = scJobId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.SC_ORG_ID
     *
     * @return the value of SC_JOB.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.SC_ORG_ID
     *
     * @param scOrgId the value for SC_JOB.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.JOB_CODE
     *
     * @return the value of SC_JOB.JOB_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.JOB_CODE
     *
     * @param jobCode the value for SC_JOB.JOB_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.JOB_NAME
     *
     * @return the value of SC_JOB.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.JOB_NAME
     *
     * @param jobName the value for SC_JOB.JOB_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.JOB_CLASS
     *
     * @return the value of SC_JOB.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getJobClass() {
        return jobClass;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.JOB_CLASS
     *
     * @param jobClass the value for SC_JOB.JOB_CLASS
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setJobClass(String jobClass) {
        this.jobClass = jobClass;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_JOB.JOB_LEVEL
     *
     * @return the value of SC_JOB.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getJobLevel() {
        return jobLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_JOB.JOB_LEVEL
     *
     * @param jobLevel the value for SC_JOB.JOB_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setJobLevel(String jobLevel) {
        this.jobLevel = jobLevel;
    }
}