package com.ei.itop.common.dbentity;

public class ScModuleI18n {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE_I18N.SC_MODULE_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private Long scModuleId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String langFlag;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE_I18N.MODULE_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String moduleName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE_I18N.MODULE_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String moduleDesc;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE_I18N.SC_MODULE_ID
     *
     * @return the value of SC_MODULE_I18N.SC_MODULE_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public Long getScModuleId() {
        return scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE_I18N.SC_MODULE_ID
     *
     * @param scModuleId the value for SC_MODULE_I18N.SC_MODULE_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setScModuleId(Long scModuleId) {
        this.scModuleId = scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE_I18N.LANG_FLAG
     *
     * @return the value of SC_MODULE_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getLangFlag() {
        return langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE_I18N.LANG_FLAG
     *
     * @param langFlag the value for SC_MODULE_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setLangFlag(String langFlag) {
        this.langFlag = langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE_I18N.MODULE_NAME
     *
     * @return the value of SC_MODULE_I18N.MODULE_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE_I18N.MODULE_NAME
     *
     * @param moduleName the value for SC_MODULE_I18N.MODULE_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE_I18N.MODULE_DESC
     *
     * @return the value of SC_MODULE_I18N.MODULE_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE_I18N.MODULE_DESC
     *
     * @param moduleDesc the value for SC_MODULE_I18N.MODULE_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc;
    }
}