package com.ei.itop.common.dbentity;

public class ScModule {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scModuleId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.SUP_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long supModuleId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.MODULE_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String moduleCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String moduleName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.MODULE_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String moduleDesc;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_MODULE.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.SC_MODULE_ID
     *
     * @return the value of SC_MODULE.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScModuleId() {
        return scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.SC_MODULE_ID
     *
     * @param scModuleId the value for SC_MODULE.SC_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScModuleId(Long scModuleId) {
        this.scModuleId = scModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.SUP_MODULE_ID
     *
     * @return the value of SC_MODULE.SUP_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getSupModuleId() {
        return supModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.SUP_MODULE_ID
     *
     * @param supModuleId the value for SC_MODULE.SUP_MODULE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setSupModuleId(Long supModuleId) {
        this.supModuleId = supModuleId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.SC_PRODUCT_ID
     *
     * @return the value of SC_MODULE.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.SC_PRODUCT_ID
     *
     * @param scProductId the value for SC_MODULE.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.SC_ORG_ID
     *
     * @return the value of SC_MODULE.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.SC_ORG_ID
     *
     * @param scOrgId the value for SC_MODULE.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.MODULE_CODE
     *
     * @return the value of SC_MODULE.MODULE_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.MODULE_CODE
     *
     * @param moduleCode the value for SC_MODULE.MODULE_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.MODULE_NAME
     *
     * @return the value of SC_MODULE.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.MODULE_NAME
     *
     * @param moduleName the value for SC_MODULE.MODULE_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.MODULE_DESC
     *
     * @return the value of SC_MODULE.MODULE_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.MODULE_DESC
     *
     * @param moduleDesc the value for SC_MODULE.MODULE_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_MODULE.STATE
     *
     * @return the value of SC_MODULE.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_MODULE.STATE
     *
     * @param state the value for SC_MODULE.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}