package com.ei.itop.common.dbentity;

public class ScOp {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOpId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String opCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String loginCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String loginPasswd;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String firstName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String opName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short gender;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short opKind;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String mobileNo;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String officeTel;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String notes;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_OP.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.SC_OP_ID
     *
     * @return the value of SC_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOpId() {
        return scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.SC_OP_ID
     *
     * @param scOpId the value for SC_OP.SC_OP_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOpId(Long scOpId) {
        this.scOpId = scOpId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.SC_ORG_ID
     *
     * @return the value of SC_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.SC_ORG_ID
     *
     * @param scOrgId the value for SC_OP.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.OP_CODE
     *
     * @return the value of SC_OP.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.OP_CODE
     *
     * @param opCode the value for SC_OP.OP_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOpCode(String opCode) {
        this.opCode = opCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.LOGIN_CODE
     *
     * @return the value of SC_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getLoginCode() {
        return loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.LOGIN_CODE
     *
     * @param loginCode the value for SC_OP.LOGIN_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setLoginCode(String loginCode) {
        this.loginCode = loginCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.LOGIN_PASSWD
     *
     * @return the value of SC_OP.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getLoginPasswd() {
        return loginPasswd;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.LOGIN_PASSWD
     *
     * @param loginPasswd the value for SC_OP.LOGIN_PASSWD
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setLoginPasswd(String loginPasswd) {
        this.loginPasswd = loginPasswd;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.FIRST_NAME
     *
     * @return the value of SC_OP.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.FIRST_NAME
     *
     * @param firstName the value for SC_OP.FIRST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.LAST_NAME
     *
     * @return the value of SC_OP.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.LAST_NAME
     *
     * @param lastName the value for SC_OP.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.OP_NAME
     *
     * @return the value of SC_OP.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.OP_NAME
     *
     * @param opName the value for SC_OP.OP_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOpName(String opName) {
        this.opName = opName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.GENDER
     *
     * @return the value of SC_OP.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.GENDER
     *
     * @param gender the value for SC_OP.GENDER
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.OP_KIND
     *
     * @return the value of SC_OP.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getOpKind() {
        return opKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.OP_KIND
     *
     * @param opKind the value for SC_OP.OP_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOpKind(Short opKind) {
        this.opKind = opKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.MOBILE_NO
     *
     * @return the value of SC_OP.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.MOBILE_NO
     *
     * @param mobileNo the value for SC_OP.MOBILE_NO
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.OFFICE_TEL
     *
     * @return the value of SC_OP.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getOfficeTel() {
        return officeTel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.OFFICE_TEL
     *
     * @param officeTel the value for SC_OP.OFFICE_TEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOfficeTel(String officeTel) {
        this.officeTel = officeTel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.NOTES
     *
     * @return the value of SC_OP.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.NOTES
     *
     * @param notes the value for SC_OP.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_OP.STATE
     *
     * @return the value of SC_OP.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_OP.STATE
     *
     * @param state the value for SC_OP.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}