package com.ei.itop.common.dbentity;

public class ScOrg {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.SUP_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long supOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.ORG_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String orgCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short orgLevel;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String orgLvlPath;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String scOrgName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String shortName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String lastName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String domainName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String domainNameSec;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String notes;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_ORG.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.SC_ORG_ID
     *
     * @return the value of SC_ORG.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.SC_ORG_ID
     *
     * @param scOrgId the value for SC_ORG.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.SUP_ORG_ID
     *
     * @return the value of SC_ORG.SUP_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getSupOrgId() {
        return supOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.SUP_ORG_ID
     *
     * @param supOrgId the value for SC_ORG.SUP_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setSupOrgId(Long supOrgId) {
        this.supOrgId = supOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.ORG_CODE
     *
     * @return the value of SC_ORG.ORG_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.ORG_CODE
     *
     * @param orgCode the value for SC_ORG.ORG_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.ORG_LEVEL
     *
     * @return the value of SC_ORG.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.ORG_LEVEL
     *
     * @param orgLevel the value for SC_ORG.ORG_LEVEL
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOrgLevel(Short orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.ORG_LVL_PATH
     *
     * @return the value of SC_ORG.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getOrgLvlPath() {
        return orgLvlPath;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.ORG_LVL_PATH
     *
     * @param orgLvlPath the value for SC_ORG.ORG_LVL_PATH
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setOrgLvlPath(String orgLvlPath) {
        this.orgLvlPath = orgLvlPath;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.SC_ORG_NAME
     *
     * @return the value of SC_ORG.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getScOrgName() {
        return scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.SC_ORG_NAME
     *
     * @param scOrgName the value for SC_ORG.SC_ORG_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgName(String scOrgName) {
        this.scOrgName = scOrgName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.SHORT_NAME
     *
     * @return the value of SC_ORG.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.SHORT_NAME
     *
     * @param shortName the value for SC_ORG.SHORT_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.LAST_NAME
     *
     * @return the value of SC_ORG.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.LAST_NAME
     *
     * @param lastName the value for SC_ORG.LAST_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.DOMAIN_NAME
     *
     * @return the value of SC_ORG.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.DOMAIN_NAME
     *
     * @param domainName the value for SC_ORG.DOMAIN_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.DOMAIN_NAME_SEC
     *
     * @return the value of SC_ORG.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getDomainNameSec() {
        return domainNameSec;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.DOMAIN_NAME_SEC
     *
     * @param domainNameSec the value for SC_ORG.DOMAIN_NAME_SEC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setDomainNameSec(String domainNameSec) {
        this.domainNameSec = domainNameSec;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.NOTES
     *
     * @return the value of SC_ORG.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.NOTES
     *
     * @param notes the value for SC_ORG.NOTES
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_ORG.STATE
     *
     * @return the value of SC_ORG.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_ORG.STATE
     *
     * @param state the value for SC_ORG.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}