package com.ei.itop.common.dbentity;

public class ScParam {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.SC_PARAM_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scParamId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.PARAM_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String paramKind;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.PARAM_KIND_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String paramKindCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.PARAM_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String paramCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.PARAM_VALUE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String paramValue;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PARAM.PARAM_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String paramDesc;
    
    private String langFlag;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.SC_PARAM_ID
     *
     * @return the value of SC_PARAM.SC_PARAM_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScParamId() {
        return scParamId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.SC_PARAM_ID
     *
     * @param scParamId the value for SC_PARAM.SC_PARAM_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScParamId(Long scParamId) {
        this.scParamId = scParamId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.SC_ORG_ID
     *
     * @return the value of SC_PARAM.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.SC_ORG_ID
     *
     * @param scOrgId the value for SC_PARAM.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.PARAM_KIND
     *
     * @return the value of SC_PARAM.PARAM_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getParamKind() {
        return paramKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.PARAM_KIND
     *
     * @param paramKind the value for SC_PARAM.PARAM_KIND
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setParamKind(String paramKind) {
        this.paramKind = paramKind;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.PARAM_KIND_CODE
     *
     * @return the value of SC_PARAM.PARAM_KIND_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getParamKindCode() {
        return paramKindCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.PARAM_KIND_CODE
     *
     * @param paramKindCode the value for SC_PARAM.PARAM_KIND_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setParamKindCode(String paramKindCode) {
        this.paramKindCode = paramKindCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.PARAM_CODE
     *
     * @return the value of SC_PARAM.PARAM_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.PARAM_CODE
     *
     * @param paramCode the value for SC_PARAM.PARAM_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.PARAM_VALUE
     *
     * @return the value of SC_PARAM.PARAM_VALUE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.PARAM_VALUE
     *
     * @param paramValue the value for SC_PARAM.PARAM_VALUE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PARAM.PARAM_DESC
     *
     * @return the value of SC_PARAM.PARAM_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PARAM.PARAM_DESC
     *
     * @param paramDesc the value for SC_PARAM.PARAM_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }

	public String getLangFlag() {
		return langFlag;
	}

	public void setLangFlag(String langFlag) {
		this.langFlag = langFlag;
	}
    
}