package com.ei.itop.common.dbentity;

public class ScProductI18n {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT_I18N.SC_PRODUCT_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String langFlag;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT_I18N.PROD_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT_I18N.PROD_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    private String prodDesc;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT_I18N.SC_PRODUCT_ID
     *
     * @return the value of SC_PRODUCT_I18N.SC_PRODUCT_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT_I18N.SC_PRODUCT_ID
     *
     * @param scProductId the value for SC_PRODUCT_I18N.SC_PRODUCT_ID
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT_I18N.LANG_FLAG
     *
     * @return the value of SC_PRODUCT_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getLangFlag() {
        return langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT_I18N.LANG_FLAG
     *
     * @param langFlag the value for SC_PRODUCT_I18N.LANG_FLAG
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setLangFlag(String langFlag) {
        this.langFlag = langFlag;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT_I18N.PROD_NAME
     *
     * @return the value of SC_PRODUCT_I18N.PROD_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT_I18N.PROD_NAME
     *
     * @param prodName the value for SC_PRODUCT_I18N.PROD_NAME
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT_I18N.PROD_DESC
     *
     * @return the value of SC_PRODUCT_I18N.PROD_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT_I18N.PROD_DESC
     *
     * @param prodDesc the value for SC_PRODUCT_I18N.PROD_DESC
     *
     * @abatorgenerated Thu Nov 27 19:19:45 CST 2014
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc;
    }
}