package com.ei.itop.common.dbentity;

public class ScProduct {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scProductId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Long scOrgId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.PROD_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String prodCode;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String prodName;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.PROD_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private String prodDesc;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SC_PRODUCT.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    private Short state;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.SC_PRODUCT_ID
     *
     * @return the value of SC_PRODUCT.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScProductId() {
        return scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.SC_PRODUCT_ID
     *
     * @param scProductId the value for SC_PRODUCT.SC_PRODUCT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScProductId(Long scProductId) {
        this.scProductId = scProductId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.SC_ORG_ID
     *
     * @return the value of SC_PRODUCT.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Long getScOrgId() {
        return scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.SC_ORG_ID
     *
     * @param scOrgId the value for SC_PRODUCT.SC_ORG_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setScOrgId(Long scOrgId) {
        this.scOrgId = scOrgId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.PROD_CODE
     *
     * @return the value of SC_PRODUCT.PROD_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getProdCode() {
        return prodCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.PROD_CODE
     *
     * @param prodCode the value for SC_PRODUCT.PROD_CODE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.PROD_NAME
     *
     * @return the value of SC_PRODUCT.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.PROD_NAME
     *
     * @param prodName the value for SC_PRODUCT.PROD_NAME
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.PROD_DESC
     *
     * @return the value of SC_PRODUCT.PROD_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.PROD_DESC
     *
     * @param prodDesc the value for SC_PRODUCT.PROD_DESC
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SC_PRODUCT.STATE
     *
     * @return the value of SC_PRODUCT.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SC_PRODUCT.STATE
     *
     * @param state the value for SC_PRODUCT.STATE
     *
     * @abatorgenerated Mon Oct 13 12:07:28 CST 2014
     */
    public void setState(Short state) {
        this.state = state;
    }
}