package com.ei.itop.common.dbentity;

public class Subscribe {
    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SUBSCRIBE.SUBSCRIBE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long subscribeId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SUBSCRIBE.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private Long icIncidentId;

    /**
     * This field was generated by AILK AUTOMATIC TOOLS.
     * This field corresponds to the database column SUBSCRIBE.SUBS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    private String subsType;

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SUBSCRIBE.SUBSCRIBE_ID
     *
     * @return the value of SUBSCRIBE.SUBSCRIBE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getSubscribeId() {
        return subscribeId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SUBSCRIBE.SUBSCRIBE_ID
     *
     * @param subscribeId the value for SUBSCRIBE.SUBSCRIBE_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setSubscribeId(Long subscribeId) {
        this.subscribeId = subscribeId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SUBSCRIBE.IC_INCIDENT_ID
     *
     * @return the value of SUBSCRIBE.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public Long getIcIncidentId() {
        return icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SUBSCRIBE.IC_INCIDENT_ID
     *
     * @param icIncidentId the value for SUBSCRIBE.IC_INCIDENT_ID
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setIcIncidentId(Long icIncidentId) {
        this.icIncidentId = icIncidentId;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method returns the value of the database column SUBSCRIBE.SUBS_TYPE
     *
     * @return the value of SUBSCRIBE.SUBS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public String getSubsType() {
        return subsType;
    }

    /**
     * This method was generated by AILK AUTOMATIC TOOLS.
     * This method sets the value of the database column SUBSCRIBE.SUBS_TYPE
     *
     * @param subsType the value for SUBSCRIBE.SUBS_TYPE
     *
     * @abatorgenerated Mon Oct 13 12:07:24 CST 2014
     */
    public void setSubsType(String subsType) {
        this.subsType = subsType;
    }
}